export const projectData = [
  {
    id: "c",
    title: "Smart Eye Glass shop",
    about: "Made for niche sunglass website. where:",
    listItem: [
      "In this website user can order a product & see his/her order details",
      "In this website user can set a review",
      "In this website user can user Cencel her/his orderd product before it's shipped",
      "In this website there is a admin route where admin do some special work. Such as make another admin, Add a product, Cencel a product from explore, see all of the order",
    ],
    category: "Niche website",
    stack: [
      "html",
      "css",
      "Bootstrap",
      "Tailwind",
      "Mongodb",
      "Express",
      "Redux",
      "Practice Project",
      "React Router",
      "Firebase",
    ],
    pointOfInterest: 80,
    backgroundColor: "#814A0E",
    link: [
      {
        code: "https://github.com/tanvir1017/Smart-Eye",
        server: "https://github.com/tanvir1017/Smart-eye-server-side",
        live: "https://smart-eye-glasses.web.app/",
      },
    ],
  },
  {
    id: "f",
    title: "Smart Eye Glass shop",
    about: "Made for niche sunglass website. where:",
    listItem: [
      "In this website user can order a product & see his/her order details",
      "In this website user can set a review",
      "In this website user can user Cencel her/his orderd product before it's shipped",
      "In this website there is a admin route where admin do some special work. Such as make another admin, Add a product, Cencel a product from explore, see all of the order",
    ],
    category: "Niche website",
    stack: [
      "html",
      "css",
      "Bootstrap",
      "Tailwind",
      "Mongodb",
      "Express",
      "Redux",
      "Practice Project",
      "React Router",
      "Firebase",
    ],
    pointOfInterest: 80,
    backgroundColor: "#814A0E",
    link: [
      {
        code: "https://github.com/tanvir1017/Smart-Eye",
        server: "https://github.com/tanvir1017/Smart-eye-server-side",
        live: "https://smart-eye-glasses.web.app/",
      },
    ],
  },
  {
    id: "a",
    title: "Smart Eye Glass shop",
    about: "Made for niche sunglass website. where:",
    listItem: [
      "In this website user can order a product & see his/her order details",
      "In this website user can set a review",
      "In this website user can user Cencel her/his orderd product before it's shipped",
      "In this website there is a admin route where admin do some special work. Such as make another admin, Add a product, Cencel a product from explore, see all of the order",
    ],
    category: "Niche website",
    stack: [
      "html",
      "css",
      "Bootstrap",
      "Tailwind",
      "Mongodb",
      "Express",
      "Redux",
      "Practice Project",
      "React Router",
      "Firebase",
    ],
    pointOfInterest: 80,
    backgroundColor: "#814A0E",
    link: [
      {
        code: "https://github.com/tanvir1017/Smart-Eye",
        server: "https://github.com/tanvir1017/Smart-eye-server-side",
        live: "https://smart-eye-glasses.web.app/",
      },
    ],
  },
  {
    id: "g",
    title: "Smart Eye Glass shop",
    about: "Made for niche sunglass website. where:",
    listItem: [
      "In this website user can order a product & see his/her order details",
      "In this website user can set a review",
      "In this website user can user Cencel her/his orderd product before it's shipped",
      "In this website there is a admin route where admin do some special work. Such as make another admin, Add a product, Cencel a product from explore, see all of the order",
    ],
    category: "Niche website",
    stack: [
      "html",
      "css",
      "Bootstrap",
      "Tailwind",
      "Mongodb",
      "Express",
      "Redux",
      "Practice Project",
      "React Router",
      "Firebase",
    ],
    pointOfInterest: 80,
    backgroundColor: "#814A0E",
    link: [
      {
        code: "https://github.com/tanvir1017/Smart-Eye",
        server: "https://github.com/tanvir1017/Smart-eye-server-side",
        live: "https://smart-eye-glasses.web.app/",
      },
    ],
  },
  {
    id: "d",
    title: "Smart Eye Glass shop",
    about: "Made for niche sunglass website. where:",
    listItem: [
      "In this website user can order a product & see his/her order details",
      "In this website user can set a review",
      "In this website user can user Cencel her/his orderd product before it's shipped",
      "In this website there is a admin route where admin do some special work. Such as make another admin, Add a product, Cencel a product from explore, see all of the order",
    ],
    category: "Niche website",
    stack: [
      "html",
      "css",
      "Bootstrap",
      "Tailwind",
      "Mongodb",
      "Express",
      "Redux",
      "Practice Project",
      "React Router",
      "Firebase",
    ],
    pointOfInterest: 80,
    backgroundColor: "#814A0E",
    link: [
      {
        code: "https://github.com/tanvir1017/Smart-Eye",
        server: "https://github.com/tanvir1017/Smart-eye-server-side",
        live: "https://smart-eye-glasses.web.app/",
      },
    ],
  },
  {
    id: "h",
    title: "Smart Eye Glass shop",
    about: "Made for niche sunglass website. where:",
    listItem: [
      "In this website user can order a product & see his/her order details",
      "In this website user can set a review",
      "In this website user can user Cencel her/his orderd product before it's shipped",
      "In this website there is a admin route where admin do some special work. Such as make another admin, Add a product, Cencel a product from explore, see all of the order",
    ],
    category: "Niche website",
    stack: [
      "html",
      "css",
      "Bootstrap",
      "Tailwind",
      "Mongodb",
      "Express",
      "Redux",
      "Practice Project",
      "React Router",
      "Firebase",
    ],
    pointOfInterest: 80,
    backgroundColor: "#814A0E",
    link: [
      {
        code: "https://github.com/tanvir1017/Smart-Eye",
        server: "https://github.com/tanvir1017/Smart-eye-server-side",
        live: "https://smart-eye-glasses.web.app/",
      },
    ],
  },
  {
    id: "e",
    title: "Smart Eye Glass shop",
    about: "Made for niche sunglass website. where:",
    listItem: [
      "In this website user can order a product & see his/her order details",
      "In this website user can set a review",
      "In this website user can user Cencel her/his orderd product before it's shipped",
      "In this website there is a admin route where admin do some special work. Such as make another admin, Add a product, Cencel a product from explore, see all of the order",
    ],
    category: "Niche website",
    stack: [
      "html",
      "css",
      "Bootstrap",
      "Tailwind",
      "Mongodb",
      "Express",
      "Redux",
      "Practice Project",
      "React Router",
      "Firebase",
    ],
    pointOfInterest: 80,
    backgroundColor: "#814A0E",
    link: [
      {
        code: "https://github.com/tanvir1017/Smart-Eye",
        server: "https://github.com/tanvir1017/Smart-eye-server-side",
        live: "https://smart-eye-glasses.web.app/",
      },
    ],
  },
  {
    id: "b",
    title: "Smart Eye Glass shop",
    about: "Made for niche sunglass website. where:",
    listItem: [
      "In this website user can order a product & see his/her order details",
      "In this website user can set a review",
      "In this website user can user Cencel her/his orderd product before it's shipped",
      "In this website there is a admin route where admin do some special work. Such as make another admin, Add a product, Cencel a product from explore, see all of the order",
    ],
    category: "Niche website",
    stack: [
      "html",
      "css",
      "Bootstrap",
      "Tailwind",
      "Mongodb",
      "Express",
      "Redux",
      "Practice Project",
      "React Router",
      "Firebase",
    ],
    pointOfInterest: 80,
    backgroundColor: "#814A0E",
    link: [
      {
        code: "https://github.com/tanvir1017/Smart-Eye",
        server: "https://github.com/tanvir1017/Smart-eye-server-side",
        live: "https://smart-eye-glasses.web.app/",
      },
    ],
  },
];
