import Head from "next/head";
import HeaderSection from "../components/header/headerSection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home | Tanvir Hossain</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HeaderSection />
      </main>
    </div>
  );
}
